### ISSUE TITLE
.tsv extensions in Windows

### ISSUE THREAD

**Issue by schnarrd** [psych-ds/example-datasets#7]
I usually export datafiles to .csv format from Excel.  I did the same to get my data for nih-reviews in .tsv format but found that Excel automatically saves tab-delimited files with a .txt extension rather than a .tsv extension.  I believe the format is otherwise identical to what you'd get from a .tsv.

In addition, it's not easy to rename the extension to a file from the basic Windows interface -- you have to use the command line. It's easy from the command line, but, if it's necessary for Psych-DS Windows users to rename each of their files as .tsvs, a lot of prospective users will simply opt out of the process entirely.

I'm not sure what the best solution to this issue is -- Psych-DS datasets could switch to a .txt extension instead of .tsv, or we could allow either .txt or .tsv, or we could provide easy tools to bypass the .tsv problem (ex very easy read-write tools).  As it stands, though, this will be a barrier to standard uptake.  In my opinion, the fewer barriers to uptake, the better.

**Comment by mekline** [comment]
This is a very good point! I'm writing to the list serv about this as we speak.
